import { Inter } from "next/font/google";
import "./globals.css";
import StoreContextProvider from "./context/StoreContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nextjs food app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreContextProvider>{children}</StoreContextProvider>
      </body>
    </html>
  );
}
